### ISSUE TITLE
Security Concern

### ISSUE THREAD

**Issue by another-guy** [jbelmont/software-testing#2]
Sir, I believe you published your private key by an accident. https://github.com/jbelmont/software-testing/blob/master/ca/key.pem

You may want to hide it ASAP (or even treat it as compromised)

**Comment by jbelmont** [comment]
@another-guy yes you have a very valid point, I mostly left it here to show others how to read certs.
With production in mind, you should never commit certificates to source repository. As I am not using this private key anywhere I created this public/private key pair for this demo application only. I will remove this private/public key pair and generate new one, as I don't want people to think this is the correct thing to do.

**Comment by another-guy** [comment]
@jbelmont oh, i am by no means judging you :) Neither did I interpret this as a good practice. I just stumbled upon the repo and noticed the cert (without knowing whether you actually use them anywhere or not). I was hoping that pointing to key.pem will help preventing any possible harm... G'day!

**Comment by jbelmont** [comment]
@another-guy no worries I am glad you brought this to my attention.
